### ISSUE TITLE
DAO resource

### ISSUE THREAD

**Issue by ke-zhang-rd** [als-computing/splash-server#17]
@dylanmcreynolds 
In [here](https://github.com/als-computing/splash-server/blob/master/splash/categories/experiments/experiments_resources.py#L9), looks we are fetching data from mongodb directly.
Should it from elastic?

Looks `current_app.db.splash.experiments` isn't set correctly.

**Comment by dylanmcreynolds** [comment]
No. This is confusing, especially on your setup. But 
`GET /api/experiments` should go to mongo.

`GET /search/* `should go to elastic.
