### ISSUE TITLE
Log all errors to console

### ISSUE THREAD

**Issue by thefearlesscoder** [als-computing/splash-server#4]
So far we do not have code in the app that will log errors to the console. We only have code that will abort the http connection sending an error response.

**Comment by thefearlesscoder** [comment]
https://damyanon.net/post/flask-series-logging/ I recommend looking here to learn how to properly handle errors.

**Comment by dylanmcreynolds** [comment]
Good points. Logging to console (rather than files) happens to be an requirement for the dockerized deployment that we will be using. I'll take this on as an enhancement.

**Comment by dylanmcreynolds** [comment]
Joshua, 

I assigned this to you. Perhaps you can lay add this to the existing code. I see a major refactor of the server.py coming, but haven't thought about it much yet. But this issue is important and won't change much with that refactor.

**Comment by thefearlesscoder** [comment]
I created a PR for this issue

**Comment by dylanmcreynolds** [comment]
Small point, but I would prefer to keep issues open until their PRs are merged. This leaves the team the ability to review and comment on the fix before declaring success.
