### ISSUE TITLE
Should we accept trailing slashes on urls?

### ISSUE THREAD

**Issue by J-avery32** [als-computing/splash-server#5]
Currently if I were to request a resource at "/foo/bar" it would return the correct resource however requesting a resource at "/foo/bar/" gives me a 404 Not Found error. Should trailing slashes be automatically removed on incoming requests?

**Comment by dylanmcreynolds** [comment]
Yes, yes they should, at least for URLs that point to non-individual resources.

For example the following two URLs should act the same: 
  foo.com/experiments
  foo.com/experiments/ 

However, a trailing slash for and individual experiment is non-sensical:
  foo.com/experiments/1234

I suggest that for these URLs, we add strict-slashed=False to the route:

@app.route('/experiments', strict_slashes=False)

**Comment by thefearlesscoder** [comment]
So are we expecting the server to abort with a 404 when an individual resource is requested with a trailing slash? Or should we issue a redirect?

**Comment by dylanmcreynolds** [comment]
Redirect would be great.
