### ISSUE TITLE
Query logic for references

### ISSUE THREAD

**Issue by dylanmcreynolds** [als-computing/splash-server#70]
https://github.com/als-computing/splash-server/blob/ca81f1be6acacfa535d3f66fb68799971d348b7d/splash/references/references_routes.py#L39

Should this query putting together (which has a lot of knowledge about mongo shema) be in the references server and not the references routes?

**Comment by thefearlesscoder** [comment]
Yes I will fix that

**Comment by thefearlesscoder** [comment]
Linking #67

**Comment by dylanmcreynolds** [comment]
Fixes #67  will do the link better than "Linking"
