### ISSUE TITLE
Should we respond with an error if the user provides a uid?

### ISSUE THREAD

**Issue by J-avery32** [als-computing/splash-server#8]
Currently if the user were to provide a uid in the document they were trying to create this would not cause an error but users are not able to specify uids. Should we respond with an error code of 400, or perhaps even specify in the schema that this is not allowed?

**Comment by dylanmcreynolds** [comment]
Yes, let's throw an error. 

I don't think that we can disallow uids in the schema, since it is valid to have it in a document (for example, in an update.)
